### PR TITLE
Add option to disable packet info

### PR DESCRIPTION
**Pull request by the-eater**

### CODE REVIEW

**Comment by vorner** [comment]
Thanks, I'll get a look at it soon.

**Comment by the-eater** [comment]
tbf was this just a quickly put together hack, now the code should be cleaner and better :) thanks for you time!

**Comment by the-eater** [comment]
The only reason I'm doing this is because I need the functionality for my pet project :see_no_evil: I'm very neglectful of projects I do not use, and since I didn't add much of value to it, I'm just going to respectfully decline your offer. I'm just a contributor nothing more.

thanks though! :)

**Comment by the-eater** [comment]
(@vorner will you make a new release for this?)

**Comment by vorner** [comment]
Not a bad idea 😇. Done.

**Pull request merged**
